spring:
  profiles:
    active: dev #指定为开发环境

#数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 1q2w3e4r5t
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      web-stat-filter:
        enabled: false
      goods:
        url: jdbc:mysql://localhost:3306/demo_goods?useUnicode=true&characterEncoding=utf8&autoReconnect=true

      member:
        url: jdbc:mysql://localhost:3306/demo_member?useUnicode=true&characterEncoding=utf8&autoReconnect=true

      sss:
        url: jdbc:mysql://localhost:3306/demo_statistics?useUnicode=true&characterEncoding=utf8&autoReconnect=true

      system:
        url: jdbc:mysql://localhost:3306/demo_system?useUnicode=true&characterEncoding=utf8&autoReconnect=true

      trade:
        url: jdbc:mysql://localhost:3306/demo_trade?useUnicode=true&characterEncoding=utf8&autoReconnect=true

      distribution:
        url: jdbc:mysql://localhost:3306/demo_distribution?useUnicode=true&characterEncoding=utf8&autoReconnect=true
